services:
  - type: web
    name: yomokka-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false

  - type: web
    name: yomokka-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
